# Generated by Django 2.0.4 on 2018-04-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
