# Generated by Django 2.0.4 on 2018-04-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20180420_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='data',
            new_name='solution',
        ),
    ]
