# Generated by Django 2.0.4 on 2018-04-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20180420_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.CharField(editable=False, max_length=30),
        ),
    ]
