# Generated by Django 2.0.4 on 2018-04-10 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
